export const LANGUAGE_WORDS = {
  en: ["test", "quiz", "study"],
  zh: ["测试", "考试", "学习"],
  es: ["prueba", "examen", "estudio"],
  hi: ["परीक्षा", "अध्ययन", "प्रश्न"],
  ar: ["اختبار", "امتحان", "تعلم"],
  bn: ["পরীক্ষা", "কুইজ", "শেখা"],
  pt: ["teste", "exame", "estudo"],
  ru: ["тест", "экзамен", "обучение"],
  ja: ["テスト", "試験", "学習"],
  pa: ["ਟੈਸਟ", "ਪ੍ਰੀਖਿਆ", "ਸਿੱਖਣਾ"],
  de: ["Test", "Prüfung", "Lernen"],
  fr: ["test", "examen", "apprentissage"],
  ko: ["시험", "테스트", "학습"],
  tr: ["sınav", "test", "öğrenme"],
  it: ["test", "esame", "studio"],
  vi: ["kiểm tra", "kỳ thi", "học"],
  ur: ["ٹیسٹ", "امتحان", "سیکھنا"],
  th: ["แบบทดสอบ", "สอบ", "เรียนรู้"],
  fa: ["آزمون", "امتحان", "یادگیری"],
  pl: ["test", "egzamin", "nauka"],
  nl: ["test", "examen", "leren"],
  id: ["tes", "ujian", "belajar"],
  ms: ["ujian", "kuiz", "pembelajaran"],
  sw: ["mtihani", "jaribio", "kujifunza"],
  ta: ["தேர்வு", "சோதனை", "கற்றல்"],
  te: ["పరీక్ష", "క్విజ్", "అభ్యాసం"],
  mr: ["परीक्षा", "चाचणी", "अध्ययन"],
  gu: ["પરીક્ષા", "ટેસ્ટ", "અભ્યાસ"],
  uk: ["тест", "іспит", "навчання"],
  ro: ["test", "examen", "învățare"],
} as const;
