export { DIFFICULTY_LADDER_BY_SUBCATEGORY } from "../../../shared/difficultyLadder";

export const DIFFICULTY_ADAPTIVE_WINDOW_SIZE = 10;
export const DIFFICULTY_PROMOTE_ACCURACY_THRESHOLD = 0.8;
export const DIFFICULTY_DEMOTE_ACCURACY_THRESHOLD = 0.5;
export const DIFFICULTY_LEVEL_CHANGE_COOLDOWN_SUBMISSIONS = 5;
