ALTER TABLE "ti"."TestSession"
ADD COLUMN "correctCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "submittedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
