export const ANONYMOUS_TTL = 60 * 60;
export const MAX_ANONYMOUS_QUESTION_COUNT = 10;
export const MAX_NON_PRO_DAILY_SUBMITTED_QUESTION_COUNT = 50;
export const MAX_RECENT_QUESTION_RESULT_COUNT = 10;
