export const ANONYMOUS_TTL = 60 * 60;
export const MAX_ANONYMOUS_QUESTION_COUNT = 10;
export const LOCAL_TEST_SESSION_MAX_QUEUED_QUESTIONS = 10;
export const LOCAL_TEST_SESSION_MIN_QUEUED_QUESTIONS = 2;
